version: "3.8"

services:

  bot:
    container_name: "bot"
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m bot
    volumes:
      - "./src:/opt/src:ro"
      - "./bot:/opt/bot:ro"
    env_file:
      - ".env"
    depends_on:
      - db

  # redis:

  migrations:
    container_name: "migrations"
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m migrations
    volumes:
      - ".:/opt:rw"
    env_file:
      - ".env"
    depends_on:
      - "db"

  db:
    container_name: "db"
    image: postgres:16-alpine3.20
    hostname: "admin"
    env_file:
      - ".env"

  server:
    container_name: "nginx"
    image: nginx:1.27.1-alpine3.20
    ports:
      - "80:80"
    env_file:
      - ".env"
    volumes:
      - "./conf.d/app.conf:/etc/nginx/conf.d/app.conf:ro"
      - "./log:/var/log/nginx:rw"
    depends_on:
      - bot
